"""
Document Template Models for Complaint & Petition Generator.
"""
import uuid
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey, Enum
from sqlalchemy.orm import relationship
from datetime import datetime
from app.db.base_class import Base
import enum


class DocumentCategory(str, enum.Enum):
    """Categories of legal documents."""
    COMPLAINT = "complaint"
    PETITION = "petition"
    APPLICATION = "application"
    NOTICE = "notice"
    AFFIDAVIT = "affidavit"
    AGREEMENT = "agreement"
    OTHER = "other"


def generate_uuid():
    return str(uuid.uuid4())


class DocumentTemplate(Base):
    """
    Stores legal document templates.
    Templates contain placeholders like {{plaintiff_name}}, {{court_name}}, etc.
    """
    id = Column(String(36), primary_key=True, default=generate_uuid, index=True)
    
    # Basic info
    name = Column(String(255), nullable=False, index=True)
    description = Column(Text, nullable=True)
    category = Column(String(50), default=DocumentCategory.OTHER.value)
    
    # Template content with placeholders
    template_content = Column(Text, nullable=False)
    
    # Required fields as JSON string (e.g., '["plaintiff_name", "defendant_name", "court_name"]')
    required_fields = Column(Text, nullable=False, default="[]")
    
    # Optional fields with descriptions as JSON
    field_descriptions = Column(Text, nullable=True)
    
    # Metadata
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by = Column(Integer, ForeignKey("user.id"), nullable=True)
    
    # Relationships
    creator = relationship("User", backref="document_templates")
    generated_documents = relationship("GeneratedDocument", back_populates="template", cascade="all, delete-orphan")


class GeneratedDocument(Base):
    """
    Stores documents generated by users from templates.
    """
    id = Column(String(36), primary_key=True, default=generate_uuid, index=True)
    
    # Reference to template
    template_id = Column(String(36), ForeignKey("documenttemplate.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("user.id"), nullable=False)
    
    # Generated content
    title = Column(String(255), nullable=False)
    content = Column(Text, nullable=False)
    
    # User input data as JSON
    input_data = Column(Text, nullable=False)
    
    # Extracted info from LLM as JSON
    extracted_fields = Column(Text, nullable=True)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    template = relationship("DocumentTemplate", back_populates="generated_documents")
    user = relationship("User", backref="generated_documents")
